global:
  scrape_interval: 30s
alerting:
  alertmanagers:
  - scheme: http
    ec2_sd_configs:
    - region: eu-west-1
      port: 9093
    relabel_configs:
    - source_labels: [__meta_ec2_tag_Name]
      regex: .*ecs-node.*
      action: keep
rule_files:
  - "/etc/prometheus/alerts/*"
scrape_configs:
  - job_name: prometheus
    scrape_interval: 5s
    static_configs:
      - targets: ['prometheus-server:9090']
  - job_name: paas-targets
    scheme: http
    proxy_url: 'http://metrics-nginx:8181'
    file_sd_configs:
      - files: ['/etc/prometheus/targets/*.json']
        refresh_interval: 30s
  - job_name: 'HTTP-blackbox-check'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - https://www.unixdaemon.net
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: prometheus-blackbox:9115
