# config file version
apiVersion: 1

# list of datasources that should be deleted from the database
deleteDatasources:
  - name: Graphite
    orgId: 1

datasources:
- name: Prometheus
  type: Prometheus
  access: direct
  isDefault: true
  url: http://prometheus-server:9090
